### ISSUE TITLE
Unexpected extension byte 

### ISSUE THREAD

**Issue by bsutton** [dart-lang/ffigen#105]
I'm trying to generate bindings for the posix libraries.

I'm getting a unhandled exception:

```
I_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _17_TIPC_MIN_LINK_TOL_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: int, usr: c:@_17_TIPC_MIN_LINK_TOL_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _17_TIPC_DEF_LINK_TOL_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: int, usr: c:@_17_TIPC_DEF_LINK_TOL_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _17_TIPC_MAX_LINK_TOL_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: int, usr: c:@_17_TIPC_MAX_LINK_TOL_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _17_TIPC_MIN_LINK_WIN_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: int, usr: c:@_17_TIPC_MIN_LINK_WIN_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _17_TIPC_DEF_LINK_WIN_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: int, usr: c:@_17_TIPC_DEF_LINK_WIN_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _17_TIPC_MAX_LINK_WIN_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: int, usr: c:@_17_TIPC_MAX_LINK_WIN_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _21_TIPC_DEF_LINK_UDP_MTU_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: int, usr: c:@_21_TIPC_DEF_LINK_UDP_MTU_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _17_TIPC_NTQ_ALLTYPES_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: unsigned int, usr: c:@_17_TIPC_NTQ_ALLTYPES_generated_macro_variable
[FINE]   : macroVariablevisitor: (Cursor) spelling: _18_TIPC_CFG_TLV_ERROR_generated_macro_variable, kind: 9, kindSpelling: VarDecl, type: 118, typeSpelling: const char *, usr: c:@_18_TIPC_CFG_TLV_ERROR_generated_macro_variable
[SEVERE] : FormatException: Unexpected extension byte (at offset 0)
[SEVERE] : #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1783:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:321:42)
#2      Utf8Codec.decode (dart:convert/utf.dart:62:20)
#3      Utf8.fromUtf8 (package:ffi/src/utf8.dart:43:17)
#4      _macroVariablevisitor (package:ffigen/src/header_parser/sub_parsers/macro_parser.dart:134:28)
#5      _FfiCallback_macroVariablevisitor (dart:ffi)
#6      FfiTrampoline (dart:ffi)
#7      Clang.clang_visitChildren_wrap (package:ffigen/src/header_parser/clang_bindings/clang_bindings.dart:498:37)
#8      parseSavedMacros (package:ffigen/src/header_parser/sub_parsers/macro_parser.dart:81:30)
#9      parseToBindings (package:ffigen/src/header_parser/parser.dart:128:19)
#10     parse (package:ffigen/src/header_parser/parser.dart:26:20)
#11     main (file:///home/bsutton/.pub-cache/hosted/pub.dartlang.org/ffigen-1.0.2/bin/ffigen.dart:54:19)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Unhandled exception:
Exception: Exception thrown in a dart function called via C, use --verbose to see more details
#0      visitChildrenResultChecker (package:ffigen/src/header_parser/utils.dart:21:5)
#1      parseSavedMacros (package:ffigen/src/header_parser/sub_parsers/macro_parser.dart:88:5)
#2      parseToBindings (package:ffigen/src/header_parser/parser.dart:128:19)
#3      parse (package:ffigen/src/header_parser/parser.dart:26:20)
#4      main (file:///home/bsutton/.pub-cache/hosted/pub.dartlang.org/ffigen-1.0.2/bin/ffigen.dart:54:19)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

My configuration is:
```
name: 'posix'
descriptions: 'Bindings to all posix apis'

output: 'generated_bindings.dart'

headers: 
  entry-points:
      - '/usr/include/linux/**.h'

array-workaround: true      

comments:
    style: doxygen
    length: full

use-supported-typedefs: true  

preamble: |
  /// AUTO GENERATED FILE, DO NOT EDIT.
  ///
  /// Generated by `package:ffigen`.
```

**Comment by mannprerak2** [comment]
Hi @bsutton, thank you for reporting this.

This particular line is to blame for this. ( the `\x` part in the string), not sure why this is happening.
```C
#define TIPC_CFG_TLV_ERROR "\x80"  /* request contains incorrect TLV(s) */
```

I'll try to fix it soon, but for the time being, you can exclude these macros (Which start with `\x`) from config like this
```yaml
macros:
  exclude:
    - 'TIPC.*'
```

**Comment by bsutton** [comment]
I've cut the generation to a single header unistd.h for the moment which has removed the error.  So thanks.
