### ISSUE TITLE
[Discussion] Should we support dart-sdk-ia32

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffigen#184]
# Background

I'm working on https://github.com/woodemi/twaindsm.dart, which implemens [TWAIN protocol](https://www.twain.org/) for scanners.

While most scanners' driver are only compatible with 32bit, I'd like to `pub run ffigen` with [dart-sdk in ia32 from archive](https://dart.dev/tools/sdk/archive)

# Problem

`dart-sdk-beta-x64` works with ffigen while `dart-sdk-beta-ia32` doen't

```sh
C:\Users\Admin\woodemi\twaindsm.dart>C:\tools\dart-sdk-beta-ia32\bin\pub run ffigen
Precompiling executable...
Precompiled ffigen:ffigen.
Running in Directory: 'C:\Users\Admin\woodemi\twaindsm.dart'
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (193)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      initParser (package:ffigen/src/header_parser/parser.dart:63:47)
#3      parse (package:ffigen/src/header_parser/parser.dart:24:3)
#4      main (file:///C:/Users/Admin/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/ffigen-1.2.0/bin/ffigen.dart:54:19)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by mannprerak2** [comment]
Since ffigen uses libclang, I think this problem should go away if you download the 32bit version of llvm. (use `llvm-lib` to supply the parent folder of dynamic library)

Also, would it not work if you'd generate the bindings with the 64bit dart sdk, but then use the bindings with 32bit one?

**Comment by Sunbreak** [comment]
Bindings generated with 64bit, works on 32bit for now. But further work may encounter problem

I'll try 32bit version of llvm when necessary

**Comment by mannprerak2** [comment]
1. For generating bindings using the 32bit dart SDK, you need to use the 32bit LLVM.
2. For generating bindings for 32bit platform using 64bit dart SDK, you can pass this -
```yaml
compiler-opts:
  - '-m32'
```

@Sunbreak Hope this helps, I'm closing this issue now.
