### ISSUE TITLE
Kernel compiler crash

### ISSUE THREAD

**Issue by dnfield** [dart-lang/ffigen#258]
ffigen 4.1.1

LLVM 13

Tried to run it on wuffs: 
https://raw.githubusercontent.com/google/wuffs/34e2786dd2e766a1800d7c55e71f024421585dd9/release/c/wuffs-v0.3.c

```yaml
ffigen:
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - 'wuffs-v0.3.c'
  llvm-path:
    - /Users/dnfield/Downloads/llvm
```

Running `dart run ffigen` does generate some `SEVERE` red warnings, but they all seem to be about `Nullability` issues in the stdlib.h from my Xcode install, e.g.

```
[SEVERE] : Header hello_library/wufs-v0.3.c: Total errors/warnings: 180.
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [Nullability Issue]
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:135:22: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [Nullability Issue]
```

When I try to `dart hello.dart` on a program that loads and uses the `NativeLibrary` generated from that, I get a kernel compiler crash:

```
Crash when compiling null,
at character offset null:
type 'InvalidType' is not a subtype of type 'InterfaceType' in type cast
#0      FfiTransformer.arraySingleElementType (package:vm/transformations/ffi/common.dart:803:50)
#1      _FfiDefinitionTransformer._checkFieldAnnotations (package:vm/transformations/ffi/definitions.dart:404:39)
#2      _FfiDefinitionTransformer.visitClass (package:vm/transformations/ffi/definitions.dart:265:25)
#3      Class.accept (package:kernel/ast.dart:1417:38)
#4      Transformer.transform (package:kernel/visitor.dart:1537:21)
#5      Transformer.transformList (package:kernel/visitor.dart:1572:18)
#6      Library.transformChildren (package:kernel/ast.dart:580:7)
#7      Transformer.defaultTreeNode (package:kernel/visitor.dart:1595:10)
#8      TreeVisitor.visitLibrary (package:kernel/visitor.dart:407:35)
#9      FfiTransformer.visitLibrary (package:vm/transformations/ffi/common.dart:504:26)
#10     List.forEach (dart:core-patch/growable_array.dart:410:8)
#11     transformLibraries (package:vm/transformations/ffi/definitions.dart:91:13)
#12     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:171:31)
#13     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1415:19)
#14     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:465:7)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#18     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#19     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#20     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#21     SingleShotCompilerWrapper.compileInternal (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#22     Compiler.compile.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#23     _processLoadRequest (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:886:37)
<asynchronous suspension>


#0      FfiTransformer.arraySingleElementType (package:vm/transformations/ffi/common.dart:803:50)
#1      _FfiDefinitionTransformer._checkFieldAnnotations (package:vm/transformations/ffi/definitions.dart:404:39)
#2      _FfiDefinitionTransformer.visitClass (package:vm/transformations/ffi/definitions.dart:265:25)
#3      Class.accept (package:kernel/ast.dart:1417:38)
#4      Transformer.transform (package:kernel/visitor.dart:1537:21)
#5      Transformer.transformList (package:kernel/visitor.dart:1572:18)
#6      Library.transformChildren (package:kernel/ast.dart:580:7)
#7      Transformer.defaultTreeNode (package:kernel/visitor.dart:1595:10)
#8      TreeVisitor.visitLibrary (package:kernel/visitor.dart:407:35)
#9      FfiTransformer.visitLibrary (package:vm/transformations/ffi/common.dart:504:26)
#10     List.forEach (dart:core-patch/growable_array.dart:410:8)
#11     transformLibraries (package:vm/transformations/ffi/definitions.dart:91:13)
#12     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:171:31)
#13     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1415:19)
#14     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:465:7)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#18     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#19     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#20     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#21     SingleShotCompilerWrapper.compileInternal (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#22     Compiler.compile.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#23     _processLoadRequest (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:886:37)
<asynchronous suspension>
```

Dart SDK version: 2.15.0-268.0.dev (dev) (Fri Oct 29 15:59:24 2021 -0700) on "macos_x64"

/cc @mraleph

**Comment by mannprerak2** [comment]
Regarding the `nullability` warnings, adding this should remove those.

```yaml
compiler-opts:
  - '-Wno-nullability-completeness'
```

**Comment by cskau-g** [comment]
I can reproduce this issue locally with:
```dart
import 'dart:ffi';
typedef T = Int64;
class A extends Struct {
  @Array.multi([16])
  external Array<T> b;
}
```
Where `Array<T>` parses as `Array<InvalidType>`.

But with a bit more fiddling I ended up with:
```
Error: Can't create typedef from non-function type.
typedef T = Int64;
```

Which led me to [this](https://dart.dev/guides/language/language-tour#typedefs):
> Version note: Before 2.13, typedefs were restricted to function types. Using the new typedefs requires a language version of at least 2.13.

And sure enough, once I updated my pubspec all issues went away:
```yaml
environment:
  sdk: '>=2.13.0 <3.0.0'
```

@dnfield you should be able to work around this issue the same way.

The bottom line here is that underlying issue is that we don't fail on the typedef error soon enough to avoid transforms getting invalid input.
I will start digging into this.
