### ISSUE TITLE
mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

### ISSUE THREAD

**Issue by arcticfox1919** [dart-lang/ffigen#323]
Executing `dart run ffigen` got the following error:

```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/Users/bruce/homebrew/opt/llvm/lib/libclang.dylib': dlopen(/Users/bruce/homebrew/opt/llvm/lib/libclang.dylib, 0x0001): tried: '/Users/bruce/homebrew/opt/llvm/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/bruce/homebrew/Cellar/llvm/13.0.1_1/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      initializeGlobals (package:ffigen/src/header_parser/data.dart:41:33)
#3      initParser (package:ffigen/src/header_parser/parser.dart:48:3)
#4      parse (package:ffigen/src/header_parser/parser.dart:22:3)
#5      main (package:ffigen/src/executables/ffigen.dart:54:19)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
I checked my Flutter environment:
```
❯ file /Users/bruce/dev_tools/flutter/bin/cache/dart-sdk/bin/dart
/Users/bruce/dev_tools/flutter/bin/cache/dart-sdk/bin/dart: Mach-O 64-bit executable x86_64
```

When I run `brew install llvm` to install llvm, what I get is a library for arm64, which I think is causing the error:

```
❯ lipo -info /Users/bruce/homebrew/Cellar/llvm/13.0.1_1/lib/libclang.dylib
Non-fat file: /Users/bruce/homebrew/Cellar/llvm/13.0.1_1/lib/libclang.dylib is architecture: arm64
```

It seems that the Flutter SDK does not have a version for Apple Silicon, so how to solve this problem?

**Comment by arcticfox1919** [comment]
I tried installing the [Dart SDK](https://dart.dev/get-dart/archive) for the Arm platform, but it still didn't work, using the standalone Dart environment, I get the following error:

```
❯ /Users/bruce/dev_tools/dart/bin/dart run ffigen
The Flutter SDK is not available.
#0      BoundSdkSource.getDirectory (package:pub/src/source/sdk.dart:125:7)
#1      SystemCache.load (package:pub/src/system_cache.dart:113:52)
#2      Entrypoint._assertLockFileUpToDate (package:pub/src/entrypoint.dart:599:19)
#3      Entrypoint.assertUpToDate (package:pub/src/entrypoint.dart:525:7)
#4      getExecutableForCommand (package:pub/src/executable.dart:304:16)
#5      RunCommand.run (package:dartdev/src/commands/run.dart:232:32)
#6      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#7      DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:30)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#9      new Future.sync (dart:async/future.dart:296:31)
#10     CommandRunner.run (package:args/command_runner.dart:119:14)
#11     runDartdev (package:dartdev/dartdev.dart:67:29)
#12     main (file:///opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
Why can't I run `ffigen` with a standalone Dart environment?

**Comment by dcharkes** [comment]
Flutter has not shipped support for Arm64 yet. You can track progress on:

* https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon
* https://github.com/flutter/flutter/issues/60118

It works with an freshly built Macos-Arm64 Dart (non Flutter) SDK:

```
dacoharkes-macbookpro2:simple dacoharkes$ ~/dart-sdk/sdk/xcodebuild/DebugARM64/dart-sdk/bin/dart run ffigen
Building package executable... (1.0s)
Built ffigen:ffigen.
Running in Directory: '/Users/dacoharkes/ffi-samples/google/ffigen/example/simple'
Input Headers: [headers/example.h]
Finished, Bindings generated in /Users/dacoharkes/ffi-samples/google/ffigen/example/simple/generated_bindings.dart
```
```
dacoharkes-macbookpro2:simple dacoharkes$ ~/dart-sdk/sdk/xcodebuild/DebugARM64/dart-sdk/bin/dart --version
Dart SDK version: 2.18.0-edge.998c74fe4709b030f0e9290923d12ad6e08d99eb (be) (Wed Apr 13 10:46:48 2022 +0200) on "macos_arm64"
```

> The Flutter SDK is not available.

Do you have a Flutter dependency in your project `pubspec.yaml`? Try temporarily removing anything flutter specific in the pubspec and run the ffigen tool.
