### ISSUE TITLE
UnimplementedError: C type unknown for BroadType.Unimplemented

### ISSUE THREAD

**Issue by PiNengShaoNian** [dart-lang/ffigen#536]
I get an error when trying to generate the ffi of the following structure, but writing the typedef of the function pointer directly in the structure does not give an error
```
typedef struct _AStruct AStruct;
typedef int (*AFunc)(AStruct *);

// Throwing exceptions
struct _AStruct
{
    AFunc func;
};

//  No errors
struct _AStruct
{
    int (*func)(AStruct *);
};
```
Here is the call stack information:
```
[WARNING]: Generated declaration '_AStruct' start's with '_' and therefore will be private.
Unhandled exception:
UnimplementedError: C type unknown for BroadType.Unimplemented
#0      Type.getCType (package:ffigen/src/code_generator/type.dart:276:9)
#1      Type.getCType (package:ffigen/src/code_generator/type.dart:254:56)
#2      Type.sameDartAndCType (package:ffigen/src/code_generator/type.dart:233:38)
#3      Type.getDartType (package:ffigen/src/code_generator/type.dart:307:29)
#4      Compound.toBindingString (package:ffigen/src/code_generator/compound.dart:119:40)
#5      Writer.generate (package:ffigen/src/code_generator/writer.dart:206:17)
#6      Library.generate (package:ffigen/src/code_generator/library.dart:132:19)
#7      Library.generateFile (package:ffigen/src/code_generator/library.dart:112:28)
#8      main (package:ffigen/src/executables/ffigen.dart:58:11)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```
os: ubuntu
dart: Dart SDK version: 2.19.4 (stable) (Unknown timestamp) on "linux_x64"
llvm: llvm-9
clang: clang6
ffigen: 4.1.2

**Comment by mannprerak2** [comment]
Try using a newer ffigen version. (Preferably the latest, 7.2.11 as of now.)

**Comment by mannprerak2** [comment]
Closing this now, this should work in newer ffigen versions.
